version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando Angular CLI y dependencias"
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo "Compilando Angular App"
      - ng build --configuration prod
  post_build:
    commands:
      - echo "Subiendo a S3"
      - aws s3 sync dist/ s3://$APP_BUCKET/ --delete
      - echo "Invalidando cache en CloudFront"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'
